/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oberamsystems.putinmon;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        //Main classUnderTest = new Main();
        String[] s = {"test", "test"};
        Main.main(s);
        //assertTrue(classUnderTest.run(), "someLibraryMethod should return 'true'");
    }
}
